[initialization]
init = false

[paths]
model_path = "model"
data_path = "data"
metadata_path = "metadata"
image_metadata_path = "metadata/image_metadata.csv"
patient_metadata_path = "metadata/patient_metadata.csv"
scan_metadata_path = "metadata/scan_metadata.csv"

