name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - ""
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion! Tell us about the feature you’d like to see.

  - type: textarea
    id: description
    attributes:
      label: "💡 Feature Description"
      description: "What is the new feature?"
      placeholder: "Explain what this feature does..."
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: "❓ Why is this needed?"
      description: "Explain why this feature would be useful."
      placeholder: "Describe the problem this feature solves."

  - type: textarea
    id: solution
    attributes:
      label: "🛠 Proposed Solution"
      description: "How should this feature work?"
      placeholder: "Describe the solution."

  - type: dropdown
    id: urgency
    attributes:
      label: "⏳ Urgency"
      description: "How soon is this needed?"
      options:
        - "🔥 Immediate – Critical feature"
        - "⚡ High – Should be implemented soon"
        - "⏳ Medium – Planned for future release"
        - "🕰️ Low – Nice to have, but not urgent"
